version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Map Redis port to host
    networks:
      - app-network

networks:
  app-network: # Define the network here
    driver: bridge